# Project 3 - Dictionaries and Dataframes

## Dictionaries

In [2]:
dct = {"run" : "to move swiftly",
      "walk" : "to move slowly, leisurely by foot"}
dct

{'run': 'to move swiftly', 'walk': 'to move slowly, leisurely by foot'}

### Dictionary Methods

In [3]:
dct.keys()

dict_keys(['run', 'walk'])

In [4]:
dct.values()

dict_values(['to move swiftly', 'to move slowly, leisurely by foot'])

In [5]:
dct.items()

dict_items([('run', 'to move swiftly'), ('walk', 'to move slowly, leisurely by foot')])

## Calling value linked to a particular key

In [6]:
# calling dictionary values
dct["run"]

'to move swiftly'

In [7]:
dct["walk"]

'to move slowly, leisurely by foot'

### Defining values on the fly

In [8]:
dct["fly"] = "to move through the air"
dct

{'run': 'to move swiftly',
 'walk': 'to move slowly, leisurely by foot',
 'fly': 'to move through the air'}

In [9]:
dct["fly"]

'to move through the air'

## Create equation using a dictionary

In [11]:
num_dct = {}
a = 3
b = 2
c = 10
for i in range(-10,11):
    num_dct[i] = a * i ** 2 + b * i + c
    
num_dct

{-10: 290,
 -9: 235,
 -8: 186,
 -7: 143,
 -6: 106,
 -5: 75,
 -4: 50,
 -3: 31,
 -2: 18,
 -1: 11,
 0: 10,
 1: 15,
 2: 26,
 3: 43,
 4: 66,
 5: 95,
 6: 130,
 7: 171,
 8: 218,
 9: 271,
 10: 330}

## Nesting a dictionary - creating more than one layer

In [12]:
dct = {
    "run":{
        "verb":"",
        "noun":""},
    "walk":{
        "verb":"",
        "noun":""}}
dct

{'run': {'verb': '', 'noun': ''}, 'walk': {'verb': '', 'noun': ''}}

In [13]:
dct["run"]["verb"] = "to move swiftly by foot"
dct["run"]["noun"] = "refers to a period of time while one was running"
dct["walk"]["verb"] = "to move slowly, liesurely by foot"
dct["walk"]["noun"] = "refers to a period of time while one was walking"
dct

{'run': {'verb': 'to move swiftly by foot',
  'noun': 'refers to a period of time while one was running'},
 'walk': {'verb': 'to move slowly, liesurely by foot',
  'noun': 'refers to a period of time while one was walking'}}

In [14]:
dct["fly"] = {"verb":"to move through the air",
             "noun":"that buzzing bug that sometimes flies around your house"}
dct

{'run': {'verb': 'to move swiftly by foot',
  'noun': 'refers to a period of time while one was running'},
 'walk': {'verb': 'to move slowly, liesurely by foot',
  'noun': 'refers to a period of time while one was walking'},
 'fly': {'verb': 'to move through the air',
  'noun': 'that buzzing bug that sometimes flies around your house'}}

## Transform a dictionary to a datafram

In [17]:
import pandas as pd
pd.DataFrame(dct)

,run,walk,fly
verb,to move swiftly by foot,"to move slowly, liesurely by foot",to move through the air
noun,refers to a period of time while one was running,refers to a period of time while one was walking,that buzzing bug that sometimes flies around y...

In [19]:
# df.T transposes the dataframe
pd.DataFrame(dct).T

,verb,noun
run,to move swiftly by foot,refers to a period of time while one was running
walk,"to move slowly, liesurely by foot",refers to a period of time while one was walking
fly,to move through the air,that buzzing bug that sometimes flies around y...

In [21]:
min_val = 0
max_val = 20
product_table = {}
for i in range(min_val, max_val + 1):
    product_table[i] = {}
    for j in range(min_val, max_val + 1):
        product_table[i][j] = i*j
        
product_table

{0: {0: 0,
  1: 0,
  2: 0,
  3: 0,
  4: 0,
  5: 0,
  6: 0,
  7: 0,
  8: 0,
  9: 0,
  10: 0,
  11: 0,
  12: 0,
  13: 0,
  14: 0,
  15: 0,
  16: 0,
  17: 0,
  18: 0,
  19: 0,
  20: 0},
 1: {0: 0,
  1: 1,
  2: 2,
  3: 3,
  4: 4,
  5: 5,
  6: 6,
  7: 7,
  8: 8,
  9: 9,
  10: 10,
  11: 11,
  12: 12,
  13: 13,
  14: 14,
  15: 15,
  16: 16,
  17: 17,
  18: 18,
  19: 19,
  20: 20},
 2: {0: 0,
  1: 2,
  2: 4,
  3: 6,
  4: 8,
  5: 10,
  6: 12,
  7: 14,
  8: 16,
  9: 18,
  10: 20,
  11: 22,
  12: 24,
  13: 26,
  14: 28,
  15: 30,
  16: 32,
  17: 34,
  18: 36,
  19: 38,
  20: 40},
 3: {0: 0,
  1: 3,
  2: 6,
  3: 9,
  4: 12,
  5: 15,
  6: 18,
  7: 21,
  8: 24,
  9: 27,
  10: 30,
  11: 33,
  12: 36,
  13: 39,
  14: 42,
  15: 45,
  16: 48,
  17: 51,
  18: 54,
  19: 57,
  20: 60},
 4: {0: 0,
  1: 4,
  2: 8,
  3: 12,
  4: 16,
  5: 20,
  6: 24,
  7: 28,
  8: 32,
  9: 36,
  10: 40,
  11: 44,
  12: 48,
  13: 52,
  14: 56,
  15: 60,
  16: 64,
  17: 68,
  18: 72,
  19: 76,
  20: 80},
 5: {0: 0,
  1: 5,
  2: 10,
  3: 15,
  4: 20,
  5: 25,
  6: 30,
  7: 35,
  8: 40,
  9: 45,
  10: 50,
  11: 55,
  12: 60,
  13: 65,
  14: 70,
  15: 75,
  16: 80,
  17: 85,
  18: 90,
  19: 95,
  20: 100},
 6: {0: 0,
  1: 6,
  2: 12,
  3: 18,
  4: 24,
  5: 30,
  6: 36,
  7: 42,
  8: 48,
  9: 54,
  10: 60,
  11: 66,
  12: 72,
  13: 78,
  14: 84,
  15: 90,
  16: 96,
  17: 102,
  18: 108,
  19: 114,
  20: 120},
 7: {0: 0,
  1: 7,
  2: 14,
  3: 21,
  4: 28,
  5: 35,
  6: 42,
  7: 49,
  8: 56,
  9: 63,
  10: 70,
  11: 77,
  12: 84,
  13: 91,
  14: 98,
  15: 105,
  16: 112,
  17: 119,
  18: 126,
  19: 133,
  20: 140},
 8: {0: 0,
  1: 8,
  2: 16,
  3: 24,
  4: 32,
  5: 40,
  6: 48,
  7: 56,
  8: 64,
  9: 72,
  10: 80,
  11: 88,
  12: 96,
  13: 104,
  14: 112,
  15: 120,
  16: 128,
  17: 136,
  18: 144,
  19: 152,
  20: 160},
 9: {0: 0,
  1: 9,
  2: 18,
  3: 27,
  4: 36,
  5: 45,
  6: 54,
  7: 63,
  8: 72,
  9: 81,
  10: 90,
  11: 99,
  12: 108,
  13: 117,
  14: 126,
  15: 135,
  16: 144,
  17: 153,
  18: 162,
  19: 171,
  20: 180},
 10: {0: 0,
  1: 10,
  2: 20,
  3: 30,
  4: 40,
  5: 50,
  6: 60,
  7: 70,
  8: 80,
  9: 90,
  10: 100,
  11: 110,
  12: 120,
  13: 130,
  14: 140,
  15: 150,
  16: 160,
  17: 170,
  18: 180,
  19: 190,
  20: 200},
 11: {0: 0,
  1: 11,
  2: 22,
  3: 33,
  4: 44,
  5: 55,
  6: 66,
  7: 77,
  8: 88,
  9: 99,
  10: 110,
  11: 121,
  12: 132,
  13: 143,
  14: 154,
  15: 165,
  16: 176,
  17: 187,
  18: 198,
  19: 209,
  20: 220},
 12: {0: 0,
  1: 12,
  2: 24,
  3: 36,
  4: 48,
  5: 60,
  6: 72,
  7: 84,
  8: 96,
  9: 108,
  10: 120,
  11: 132,
  12: 144,
  13: 156,
  14: 168,
  15: 180,
  16: 192,
  17: 204,
  18: 216,
  19: 228,
  20: 240},
 13: {0: 0,
  1: 13,
  2: 26,
  3: 39,
  4: 52,
  5: 65,
  6: 78,
  7: 91,
  8: 104,
  9: 117,
  10: 130,
  11: 143,
  12: 156,
  13: 169,
  14: 182,
  15: 195,
  16: 208,
  17: 221,
  18: 234,
  19: 247,
  20: 260},
 14: {0: 0,
  1: 14,
  2: 28,
  3: 42,
  4: 56,
  5: 70,
  6: 84,
  7: 98,
  8: 112,
  9: 126,
  10: 140,
  11: 154,
  12: 168,
  13: 182,
  14: 196,
  15: 210,
  16: 224,
  17: 238,
  18: 252,
  19: 266,
  20: 280},
 15: {0: 0,
  1: 15,
  2: 30,
  3: 45,
  4: 60,
  5: 75,
  6: 90,
  7: 105,
  8: 120,
  9: 135,
  10: 150,
  11: 165,
  12: 180,
  13: 195,
  14: 210,
  15: 225,
  16: 240,
  17: 255,
  18: 270,
  19: 285,
  20: 300},
 16: {0: 0,
  1: 16,
  2: 32,
  3: 48,
  4: 64,
  5: 80,
  6: 96,
  7: 112,
  8: 128,
  9: 144,
  10: 160,
  11: 176,
  12: 192,
  13: 208,
  14: 224,
  15: 240,
  16: 256,
  17: 272,
  18: 288,
  19: 304,
  20: 320},
 17: {0: 0,
  1: 17,
  2: 34,
  3: 51,
  4: 68,
  5: 85,
  6: 102,
  7: 119,
  8: 136,
  9: 153,
  10: 170,
  11: 187,
  12: 204,
  13: 221,
  14: 238,
  15: 255,
  16: 272,
  17: 289,
  18: 306,
  19: 323,
  20: 340},
 18: {0: 0,
  1: 18,
  2: 36,
  3: 54,
  4: 72,
  5: 90,
  6: 108,
  7: 126,
  8: 144,
  9: 162,
  10: 180,
  11: 198,
  12: 216,
  13: 234,
  14: 252,
  15: 270,
  16: 288,
  17: 306,
  18: 324,
  19: 342,
  20: 360},
 19: {0: 0,
  1: 19,
  2: 38,
  3: 57,
  4: 76,
  5: 95,
  6: 114,
  7: 133,
  8: 152,
  9: 171,
  10: 190,
  11: 209,
  12: 228,
  13: 247,
  14: 266,
  15: 285,
  16: 304,
  17: 323,
  18: 342,
  19: 361,
  20: 380},
 20: {0: 0,
  1: 20,
  2: 40,
  3: 60,
  4: 80,
  5: 100,
  6: 120,
  7: 140,
  8: 160,
  9: 180,
  10: 200,
  11: 220,
  12: 240,
  13: 260,
  14: 280,
  15: 300,
  16: 320,
  17: 340,
  18: 360,
  19: 380,
  20: 400}}

In [22]:
pd.DataFrame(product_table)

,0,1,2,3,4,5,6,7,8,9,...,11,12,13,14,15,16,17,18,19,20
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,1,2,3,4,5,6,7,8,9,...,11,12,13,14,15,16,17,18,19,20
2,0,2,4,6,8,10,12,14,16,18,...,22,24,26,28,30,32,34,36,38,40
3,0,3,6,9,12,15,18,21,24,27,...,33,36,39,42,45,48,51,54,57,60
4,0,4,8,12,16,20,24,28,32,36,...,44,48,52,56,60,64,68,72,76,80
5,0,5,10,15,20,25,30,35,40,45,...,55,60,65,70,75,80,85,90,95,100
6,0,6,12,18,24,30,36,42,48,54,...,66,72,78,84,90,96,102,108,114,120
7,0,7,14,21,28,35,42,49,56,63,...,77,84,91,98,105,112,119,126,133,140
8,0,8,16,24,32,40,48,56,64,72,...,88,96,104,112,120,128,136,144,152,160
9,0,9,18,27,36,45,54,63,72,81,...,99,108,117,126,135,144,153,162,171,180
10,0,10,20,30,40,50,60,70,80,90,...,110,120,130,140,150,160,170,180,190,200
11,0,11,22,33,44,55,66,77,88,99,...,121,132,143,154,165,176,187,198,209,220
12,0,12,24,36,48,60,72,84,96,108,...,132,144,156,168,180,192,204,216,228,240
13,0,13,26,39,52,65,78,91,104,117,...,143,156,169,182,195,208,221,234,247,260
14,0,14,28,42,56,70,84,98,112,126,...,154,168,182,196,210,224,238,252,266,280
15,0,15,30,45,60,75,90,105,120,135,...,165,180,195,210,225,240,255,270,285,300
16,0,16,32,48,64,80,96,112,128,144,...,176,192,208,224,240,256,272,288,304,320
17,0,17,34,51,68,85,102,119,136,153,...,187,204,221,238,255,272,289,306,323,340
18,0,18,36,54,72,90,108,126,144,162,...,198,216,234,252,270,288,306,324,342,360
19,0,19,38,57,76,95,114,133,152,171,...,209,228,247,266,285,304,323,342,361,380
20,0,20,40,60,80,100,120,140,160,180,...,220,240,260,280,300,320,340,360,380,400

In [25]:
## build a dictionary with faculty information
# will build the first few rows

faculty_dct = {
                "Bangsund, Dean": {"Position": "Research Scientist",
                                  "Email": "d.bangsund@ndsu.edu",
                                  "Phone":"701-231-7471"},
                "Biermacher, Jon": {"Position": "Extension Livestock Development Specialist",
                                  "Email": "jon.biermacher@ndsu.edu",
                                  "Phone":"701-231-7379"}
}

faculty_dct

{'Bangsund, Dean': {'Position': 'Research Scientist',
  'Email': 'd.bangsund@ndsu.edu',
  'Phone': '701-231-7471'},
 'Biermacher, Jon': {'Position': 'Extension Livestock Development Specialist',
  'Email': 'jon.biermacher@ndsu.edu',
  'Phone': '701-231-7379'}}

In [26]:
pd.DataFrame(faculty_dct).T

,Position,Email,Phone
"Bangsund, Dean",Research Scientist,d.bangsund@ndsu.edu,701-231-7471
"Biermacher, Jon",Extension Livestock Development Specialist,jon.biermacher@ndsu.edu,701-231-7379

In [27]:
# To get it from excel

# faculty_df = pd.read_csv("NDSUFaculty.csv")
#faculty_df

In [28]:
#to get phone numbers from excel file
#phone_numbers = faculty_df[["Phone"]]
#phone_numbers